# @generated
from .core import Element

def html(*inner, **kwargs) -> Element:
    return Element('html', inner, {'manifest': kwargs.pop('manifest', None), 'xmlns': kwargs.pop('xmlns', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def head(*inner, **kwargs) -> Element:
    return Element('head', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def title(*inner, **kwargs) -> Element:
    return Element('title', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def base(*inner, **kwargs) -> Element:
    return Element('base', inner, {'href': kwargs.pop('href', None), 'target': kwargs.pop('target', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def link(*inner, **kwargs) -> Element:
    return Element('link', inner, { **kwargs})

def meta(*inner, **kwargs) -> Element:
    return Element('meta', inner, { **kwargs})

def body(*inner, **kwargs) -> Element:
    return Element('body', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def article(*inner, **kwargs) -> Element:
    return Element('article', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def section(*inner, **kwargs) -> Element:
    return Element('section', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def nav(*inner, **kwargs) -> Element:
    return Element('nav', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def aside(*inner, **kwargs) -> Element:
    return Element('aside', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def h1(*inner, **kwargs) -> Element:
    return Element('h1', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def h2(*inner, **kwargs) -> Element:
    return Element('h2', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def h3(*inner, **kwargs) -> Element:
    return Element('h3', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def h4(*inner, **kwargs) -> Element:
    return Element('h4', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def h5(*inner, **kwargs) -> Element:
    return Element('h5', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def h6(*inner, **kwargs) -> Element:
    return Element('h6', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def header(*inner, **kwargs) -> Element:
    return Element('header', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def footer(*inner, **kwargs) -> Element:
    return Element('footer', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def address(*inner, **kwargs) -> Element:
    return Element('address', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def p(*inner, **kwargs) -> Element:
    return Element('p', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def hr(*inner, **kwargs) -> Element:
    return Element('hr', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def pre(*inner, **kwargs) -> Element:
    return Element('pre', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def blockquote(*inner, **kwargs) -> Element:
    return Element('blockquote', inner, {'cite': kwargs.pop('cite', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def ol(*inner, **kwargs) -> Element:
    return Element('ol', inner, {'reversed': kwargs.pop('reversed', None), 'start': kwargs.pop('start', None), 'type': kwargs.pop('type', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def ul(*inner, **kwargs) -> Element:
    return Element('ul', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def menu(*inner, **kwargs) -> Element:
    return Element('menu', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def li(*inner, **kwargs) -> Element:
    return Element('li', inner, {'value': kwargs.pop('value', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def dl(*inner, **kwargs) -> Element:
    return Element('dl', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def dt(*inner, **kwargs) -> Element:
    return Element('dt', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def dd(*inner, **kwargs) -> Element:
    return Element('dd', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def figure(*inner, **kwargs) -> Element:
    return Element('figure', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def figcaption(*inner, **kwargs) -> Element:
    return Element('figcaption', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def main(*inner, **kwargs) -> Element:
    return Element('main', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def div(*inner, **kwargs) -> Element:
    return Element('div', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def a(*inner, **kwargs) -> Element:
    return Element('a', inner, {'href': kwargs.pop('href', None), 'target': kwargs.pop('target', None), 'download': kwargs.pop('download', None), 'rel': kwargs.pop('rel', None), 'hreflang': kwargs.pop('hreflang', None), 'type': kwargs.pop('type', None), 'referrerpolicy': kwargs.pop('referrerpolicy', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def em(*inner, **kwargs) -> Element:
    return Element('em', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def strong(*inner, **kwargs) -> Element:
    return Element('strong', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def small(*inner, **kwargs) -> Element:
    return Element('small', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def s(*inner, **kwargs) -> Element:
    return Element('s', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def cite(*inner, **kwargs) -> Element:
    return Element('cite', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def q(*inner, **kwargs) -> Element:
    return Element('q', inner, {'cite': kwargs.pop('cite', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def dfn(*inner, **kwargs) -> Element:
    return Element('dfn', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def abbr(*inner, **kwargs) -> Element:
    return Element('abbr', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def ruby(*inner, **kwargs) -> Element:
    return Element('ruby', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def rt(*inner, **kwargs) -> Element:
    return Element('rt', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def rp(*inner, **kwargs) -> Element:
    return Element('rp', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def data(*inner, **kwargs) -> Element:
    return Element('data', inner, {'value': kwargs.pop('value', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def time(*inner, **kwargs) -> Element:
    return Element('time', inner, {'datetime': kwargs.pop('datetime', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def code(*inner, **kwargs) -> Element:
    return Element('code', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def var(*inner, **kwargs) -> Element:
    return Element('var', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def samp(*inner, **kwargs) -> Element:
    return Element('samp', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def kbd(*inner, **kwargs) -> Element:
    return Element('kbd', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def sub(*inner, **kwargs) -> Element:
    return Element('sub', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def sup(*inner, **kwargs) -> Element:
    return Element('sup', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def i(*inner, **kwargs) -> Element:
    return Element('i', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def b(*inner, **kwargs) -> Element:
    return Element('b', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def u(*inner, **kwargs) -> Element:
    return Element('u', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def mark(*inner, **kwargs) -> Element:
    return Element('mark', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def bdi(*inner, **kwargs) -> Element:
    return Element('bdi', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def bdo(*inner, **kwargs) -> Element:
    return Element('bdo', inner, {'dir': kwargs.pop('dir', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def span(*inner, **kwargs) -> Element:
    return Element('span', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def br(*inner, **kwargs) -> Element:
    return Element('br', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def wbr(*inner, **kwargs) -> Element:
    return Element('wbr', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def ins(*inner, **kwargs) -> Element:
    return Element('ins', inner, {'cite': kwargs.pop('cite', None), 'datetime': kwargs.pop('datetime', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def del_(*inner, **kwargs) -> Element:
    return Element('del', inner, {'cite': kwargs.pop('cite', None), 'datetime': kwargs.pop('datetime', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def picture(*inner, **kwargs) -> Element:
    return Element('picture', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def source(*inner, **kwargs) -> Element:
    return Element('source', inner, {'src': kwargs.pop('src', None), 'srcset': kwargs.pop('srcset', None), 'sizes': kwargs.pop('sizes', None), 'media': kwargs.pop('media', None), 'type': kwargs.pop('type', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def img(*inner, **kwargs) -> Element:
    return Element('img', inner, {'alt': kwargs.pop('alt', None), 'src': kwargs.pop('src', None), 'srcset': kwargs.pop('srcset', None), 'sizes': kwargs.pop('sizes', None), 'crossorigin': kwargs.pop('crossorigin', None), 'usemap': kwargs.pop('usemap', None), 'ismap': kwargs.pop('ismap', None), 'width': kwargs.pop('width', None), 'height': kwargs.pop('height', None), 'referrerpolicy': kwargs.pop('referrerpolicy', None), 'decoding': kwargs.pop('decoding', None), 'loading': kwargs.pop('loading', None), 'fetchpriority': kwargs.pop('fetchpriority', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def iframe(*inner, **kwargs) -> Element:
    return Element('iframe', inner, {'src': kwargs.pop('src', None), 'srcdoc': kwargs.pop('srcdoc', None), 'name': kwargs.pop('name', None), 'sandbox': kwargs.pop('sandbox', None), 'allow': kwargs.pop('allow', None), 'allowfullscreen': kwargs.pop('allowfullscreen', None), 'width': kwargs.pop('width', None), 'height': kwargs.pop('height', None), 'referrerpolicy': kwargs.pop('referrerpolicy', None), 'loading': kwargs.pop('loading', None), 'credentialless': kwargs.pop('credentialless', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def embed(*inner, **kwargs) -> Element:
    return Element('embed', inner, {'src': kwargs.pop('src', None), 'type': kwargs.pop('type', None), 'width': kwargs.pop('width', None), 'height': kwargs.pop('height', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def object(*inner, **kwargs) -> Element:
    return Element('object', inner, {'data': kwargs.pop('data', None), 'type': kwargs.pop('type', None), 'name': kwargs.pop('name', None), 'form': kwargs.pop('form', None), 'width': kwargs.pop('width', None), 'height': kwargs.pop('height', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def video(*inner, **kwargs) -> Element:
    return Element('video', inner, {'src': kwargs.pop('src', None), 'crossorigin': kwargs.pop('crossorigin', None), 'poster': kwargs.pop('poster', None), 'preload': kwargs.pop('preload', None), 'autoplay': kwargs.pop('autoplay', None), 'playsinline': kwargs.pop('playsinline', None), 'loop': kwargs.pop('loop', None), 'muted': kwargs.pop('muted', None), 'controls': kwargs.pop('controls', None), 'width': kwargs.pop('width', None), 'height': kwargs.pop('height', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def audio(*inner, **kwargs) -> Element:
    return Element('audio', inner, {'src': kwargs.pop('src', None), 'crossorigin': kwargs.pop('crossorigin', None), 'preload': kwargs.pop('preload', None), 'autoplay': kwargs.pop('autoplay', None), 'loop': kwargs.pop('loop', None), 'muted': kwargs.pop('muted', None), 'controls': kwargs.pop('controls', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def track(*inner, **kwargs) -> Element:
    return Element('track', inner, {'default': kwargs.pop('default', None), 'kind': kwargs.pop('kind', None), 'label': kwargs.pop('label', None), 'src': kwargs.pop('src', None), 'srclang': kwargs.pop('srclang', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def canvas(*inner, **kwargs) -> Element:
    return Element('canvas', inner, {'width': kwargs.pop('width', None), 'height': kwargs.pop('height', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def table(*inner, **kwargs) -> Element:
    return Element('table', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def caption(*inner, **kwargs) -> Element:
    return Element('caption', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def colgroup(*inner, **kwargs) -> Element:
    return Element('colgroup', inner, {'span': kwargs.pop('span', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def col(*inner, **kwargs) -> Element:
    return Element('col', inner, {'span': kwargs.pop('span', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def tbody(*inner, **kwargs) -> Element:
    return Element('tbody', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def thead(*inner, **kwargs) -> Element:
    return Element('thead', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def tfoot(*inner, **kwargs) -> Element:
    return Element('tfoot', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def tr(*inner, **kwargs) -> Element:
    return Element('tr', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def td(*inner, **kwargs) -> Element:
    return Element('td', inner, {'colspan': kwargs.pop('colspan', None), 'rowspan': kwargs.pop('rowspan', None), 'headers': kwargs.pop('headers', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def th(*inner, **kwargs) -> Element:
    return Element('th', inner, {'colspan': kwargs.pop('colspan', None), 'rowspan': kwargs.pop('rowspan', None), 'headers': kwargs.pop('headers', None), 'scope': kwargs.pop('scope', None), 'abbr': kwargs.pop('abbr', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def form(*inner, **kwargs) -> Element:
    return Element('form', inner, {'accept-charset': kwargs.pop('accept_charset', None), 'action': kwargs.pop('action', None), 'autocomplete': kwargs.pop('autocomplete', None), 'enctype': kwargs.pop('enctype', None), 'method': kwargs.pop('method', None), 'name': kwargs.pop('name', None), 'novalidate': kwargs.pop('novalidate', None), 'target': kwargs.pop('target', None), 'rel': kwargs.pop('rel', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def label(*inner, **kwargs) -> Element:
    return Element('label', inner, {'for': kwargs.pop('for_', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def input(*inner, **kwargs) -> Element:
    return Element('input', inner, {'accept': kwargs.pop('accept', None), 'alt': kwargs.pop('alt', None), 'autocomplete': kwargs.pop('autocomplete', None), 'capture': kwargs.pop('capture', None), 'checked': kwargs.pop('checked', None), 'dirname': kwargs.pop('dirname', None), 'disabled': kwargs.pop('disabled', None), 'form': kwargs.pop('form', None), 'formaction': kwargs.pop('formaction', None), 'formenctype': kwargs.pop('formenctype', None), 'formmethod': kwargs.pop('formmethod', None), 'formnovalidate': kwargs.pop('formnovalidate', None), 'formtarget': kwargs.pop('formtarget', None), 'height': kwargs.pop('height', None), 'list': kwargs.pop('list', None), 'max': kwargs.pop('max', None), 'maxlength': kwargs.pop('maxlength', None), 'min': kwargs.pop('min', None), 'minlength': kwargs.pop('minlength', None), 'multiple': kwargs.pop('multiple', None), 'name': kwargs.pop('name', None), 'pattern': kwargs.pop('pattern', None), 'placeholder': kwargs.pop('placeholder', None), 'popovertarget': kwargs.pop('popovertarget', None), 'popovertargetaction': kwargs.pop('popovertargetaction', None), 'readonly': kwargs.pop('readonly', None), 'required': kwargs.pop('required', None), 'size': kwargs.pop('size', None), 'src': kwargs.pop('src', None), 'step': kwargs.pop('step', None), 'type': kwargs.pop('type', None), 'value': kwargs.pop('value', None), 'width': kwargs.pop('width', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def button(*inner, **kwargs) -> Element:
    return Element('button', inner, {'disabled': kwargs.pop('disabled', None), 'form': kwargs.pop('form', None), 'formaction': kwargs.pop('formaction', None), 'formenctype': kwargs.pop('formenctype', None), 'formmethod': kwargs.pop('formmethod', None), 'formnovalidate': kwargs.pop('formnovalidate', None), 'formtarget': kwargs.pop('formtarget', None), 'name': kwargs.pop('name', None), 'popovertarget': kwargs.pop('popovertarget', None), 'popovertargetaction': kwargs.pop('popovertargetaction', None), 'type': kwargs.pop('type', None), 'value': kwargs.pop('value', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def select(*inner, **kwargs) -> Element:
    return Element('select', inner, {'autocomplete': kwargs.pop('autocomplete', None), 'disabled': kwargs.pop('disabled', None), 'form': kwargs.pop('form', None), 'multiple': kwargs.pop('multiple', None), 'name': kwargs.pop('name', None), 'required': kwargs.pop('required', None), 'size': kwargs.pop('size', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def datalist(*inner, **kwargs) -> Element:
    return Element('datalist', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def optgroup(*inner, **kwargs) -> Element:
    return Element('optgroup', inner, {'disabled': kwargs.pop('disabled', None), 'label': kwargs.pop('label', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def option(*inner, **kwargs) -> Element:
    return Element('option', inner, {'disabled': kwargs.pop('disabled', None), 'label': kwargs.pop('label', None), 'selected': kwargs.pop('selected', None), 'value': kwargs.pop('value', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def textarea(*inner, **kwargs) -> Element:
    return Element('textarea', inner, {'autocomplete': kwargs.pop('autocomplete', None), 'cols': kwargs.pop('cols', None), 'dirname': kwargs.pop('dirname', None), 'disabled': kwargs.pop('disabled', None), 'form': kwargs.pop('form', None), 'maxlength': kwargs.pop('maxlength', None), 'minlength': kwargs.pop('minlength', None), 'name': kwargs.pop('name', None), 'placeholder': kwargs.pop('placeholder', None), 'readonly': kwargs.pop('readonly', None), 'required': kwargs.pop('required', None), 'rows': kwargs.pop('rows', None), 'wrap': kwargs.pop('wrap', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def output(*inner, **kwargs) -> Element:
    return Element('output', inner, {'for': kwargs.pop('for_', None), 'form': kwargs.pop('form', None), 'name': kwargs.pop('name', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def progress(*inner, **kwargs) -> Element:
    return Element('progress', inner, {'max': kwargs.pop('max', None), 'value': kwargs.pop('value', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def meter(*inner, **kwargs) -> Element:
    return Element('meter', inner, {'value': kwargs.pop('value', None), 'min': kwargs.pop('min', None), 'max': kwargs.pop('max', None), 'low': kwargs.pop('low', None), 'high': kwargs.pop('high', None), 'optimum': kwargs.pop('optimum', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def fieldset(*inner, **kwargs) -> Element:
    return Element('fieldset', inner, {'disabled': kwargs.pop('disabled', None), 'form': kwargs.pop('form', None), 'name': kwargs.pop('name', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def legend(*inner, **kwargs) -> Element:
    return Element('legend', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def details(*inner, **kwargs) -> Element:
    return Element('details', inner, {'open': kwargs.pop('open', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def summary(*inner, **kwargs) -> Element:
    return Element('summary', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def dialog(*inner, **kwargs) -> Element:
    return Element('dialog', inner, {'open': kwargs.pop('open', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def script(*inner, **kwargs) -> Element:
    return Element('script', inner, { **kwargs})

def noscript(*inner, **kwargs) -> Element:
    return Element('noscript', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def template(*inner, **kwargs) -> Element:
    return Element('template', inner, {'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

def slot(*inner, **kwargs) -> Element:
    return Element('slot', inner, {'name': kwargs.pop('name', None), 'accesskey': kwargs.pop('accesskey', None), 'class': kwargs.pop('class_', None), 'style': kwargs.pop('style', None), 'contenteditable': kwargs.pop('contenteditable', None), 'dir': kwargs.pop('dir', None), 'draggable': kwargs.pop('draggable', None), 'hidden': kwargs.pop('hidden', None), 'id': kwargs.pop('id', None), 'lang': kwargs.pop('lang', None), 'spellcheck': kwargs.pop('spellcheck', None), 'tabindex': kwargs.pop('tabindex', None), 'title': kwargs.pop('title', None), **kwargs})

